# Generated by Django 5.2 on 2025-06-13 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('immobile', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_data', models.DateField()),
                ('end_data', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Ativado'), ('finished', 'Finalizado'), ('canceled', 'Cancelado')], default='active', max_length=15)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('immobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='immobile.immobile')),
            ],
        ),
    ]
