# Generated by Django 5.2 on 2025-04-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_owner_delete_financeiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='total_properties',
        ),
    ]
