# Generated by Django 5.2 on 2025-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_remove_owner_total_properties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='member_since',
        ),
        migrations.AlterField(
            model_name='owner',
            name='about_me',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
