# Generated by Django 5.2 on 2025-04-10 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.PositiveIntegerField()),
                ('emprego', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('sobre_mim', models.TextField()),
                ('prefere_kitnet', models.BooleanField(default=False)),
                ('prefere_apartamento', models.BooleanField(default=False)),
                ('prefere_dividir_aluguel', models.BooleanField(default=False)),
                ('aceita_pets', models.BooleanField(default=False)),
                ('nota_usuario', models.FloatField(default=0.0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inquilino_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
