# Generated by Django 5.2 on 2025-05-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('job', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('about_me', models.TextField()),
                ('prefers_studio', models.BooleanField(default=False)),
                ('prefers_apartment', models.BooleanField(default=False)),
                ('prefers_shared_rent', models.BooleanField(default=False)),
                ('accepts_pets', models.BooleanField(default=False)),
                ('user_rating', models.FloatField(default=0.0)),
                ('properties_rented', models.PositiveIntegerField(default=0)),
                ('rated_by_landlords', models.PositiveIntegerField(default=0)),
                ('recommended_by_landlords', models.PositiveIntegerField(default=0)),
                ('favorited_properties', models.PositiveIntegerField(default=0)),
                ('fast_responder', models.BooleanField(default=False)),
                ('member_since', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
