# Generated by Django 5.2 on 2025-04-11 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('job', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('about_me', models.TextField()),
                ('prefers_studio', models.BooleanField(default=False)),
                ('prefers_apartment', models.BooleanField(default=False)),
                ('prefers_shared_rent', models.BooleanField(default=False)),
                ('accepts_pets', models.BooleanField(default=False)),
                ('user_rating', models.FloatField(default=0.0)),
                ('properties_rented', models.PositiveIntegerField(default=0)),
                ('rated_by_landlords', models.PositiveIntegerField(default=0)),
                ('recommended_by_landlords', models.PositiveIntegerField(default=0)),
                ('favorited_properties', models.PositiveIntegerField(default=0)),
                ('fast_responder', models.BooleanField(default=False)),
                ('member_since', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TenantRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True, null=True)),
                ('recommended', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='tenant.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'rated_by')},
            },
        ),
        migrations.DeleteModel(
            name='Inquilino',
        ),
    ]
