# Generated by Django 5.2 on 2025-06-13 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('RENTED_CONFIRMATION', 'Confirmação de Aluguel'), ('PAYMENT_RECEIVED', 'Pagamento Recebido'), ('REVIEW_RECEIVED', 'Avaliação Recebida'), ('GENERAL', 'Geral')], default='GENERAL', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
