# Generated by Django 5.2 on 2025-05-04 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Immobile',
            fields=[
                ('id_immobile', models.AutoField(primary_key=True, serialize=False)),
                ('property_type', models.CharField(choices=[('house', 'Casa'), ('apartment', 'Apartamento'), ('kitnet', 'Kitnet')], default='House', max_length=20)),
                ('zip_code', models.CharField(max_length=9)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(blank=True, max_length=10)),
                ('no_number', models.BooleanField(default=False)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('garage', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('nearby_market', models.BooleanField(default=False)),
                ('nearby_bus', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('additional_rules', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Available', 'Disponível'), ('Rented', 'Alugada'), ('Unavailable', 'Indisponível')], default='Available', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ImmobilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_blob', models.BinaryField(default=bytes)),
                ('content_type', models.CharField(default='', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_received', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
