# Generated by Django 5.2 on 2025-04-11 01:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Immobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_immobile', models.IntegerField()),
                ('tipo', models.CharField(choices=[('Casa', 'Casa'), ('Apartamento', 'Apartamento'), ('Kitnet', 'Kitnet'), ('Sala comercial', 'Sala comercial')], max_length=20)),
                ('cep', models.CharField(max_length=9)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(blank=True, max_length=10)),
                ('sem_numero', models.BooleanField(default=False)),
                ('quartos', models.IntegerField()),
                ('banheiros', models.IntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('aluguel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ar_condicionado', models.BooleanField(default=False)),
                ('garagem', models.BooleanField(default=False)),
                ('piscina', models.BooleanField(default=False)),
                ('mobiliado', models.BooleanField(default=False)),
                ('permite_animais', models.BooleanField(default=False)),
                ('mercado_proximo', models.BooleanField(default=False)),
                ('onibus_proximo', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('descricao', models.TextField()),
                ('regras_adicionais', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Disponível', 'Disponível'), ('Alugado', 'Alugado')], default='Disponível', max_length=10)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
