# Generated by Django 5.2 on 2025-04-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='immobile',
            old_name='regras_adicionais',
            new_name='additional_rules',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='ar_condicionado',
            new_name='air_conditioning',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='banheiros',
            new_name='bathrooms',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='quartos',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='cidade',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='data_cadastro',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='mobiliado',
            new_name='furnished',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='garagem',
            new_name='garage',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='onibus_proximo',
            new_name='nearby_bus',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='mercado_proximo',
            new_name='nearby_market',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='sem_numero',
            new_name='no_number',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='numero',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='permite_animais',
            new_name='pet_friendly',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='piscina',
            new_name='pool',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='aluguel',
            new_name='rent',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='estado',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='rua',
            new_name='street',
        ),
        migrations.RenameField(
            model_name='immobile',
            old_name='cep',
            new_name='zip_code',
        ),
        migrations.RemoveField(
            model_name='immobile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='immobile',
            name='tipo',
        ),
        migrations.AddField(
            model_name='immobile',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment')], default='House', max_length=20),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='id_immobile',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Rented', 'Rented'), ('Unavailable', 'Unavailable')], default='Available', max_length=15),
        ),
    ]
