# Generated by Django 5.2 on 2025-05-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('immobile', '0001_initial'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='owner.owner'),
        ),
        migrations.AddField(
            model_name='immobilephoto',
            name='immobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_blob', to='immobile.immobile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='immobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='immobile.immobile'),
        ),
    ]
