# Generated by Django 5.2 on 2025-04-15 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobile', '0002_rename_regras_adicionais_immobile_additional_rules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('cpf_cnpj', models.CharField(max_length=20, unique=True)),
                ('postal_code', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=100)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('no_number', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('immobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='immobile.immobile')),
            ],
        ),
    ]
