# Generated by Django 5.2 on 2025-04-28 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobile', '0002_rename_regras_adicionais_immobile_additional_rules_and_more'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='owner.owner'),
        ),
    ]
