# Generated by Django 5.2 on 2025-06-13 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('immobile', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='immobile',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='immobilephoto',
            name='immobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_blob', to='immobile.immobile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='immobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='immobile.immobile'),
        ),
    ]
