# Generated by Django 5.2 on 2025-04-19 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobile', '0003_owner_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmobilePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='immobile_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
        migrations.AlterField(
            model_name='immobile',
            name='id_immobile',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='immobilephoto',
            name='immobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='immobile.immobile'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
