# Generated by Django 5.2 on 2025-04-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobile', '0004_immobilephoto_delete_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immobile',
            name='property_type',
            field=models.CharField(choices=[('house', 'Casa'), ('apartment', 'Apartamento'), ('kitnet', 'Kitnet')], default='House', max_length=20),
        ),
        migrations.AlterField(
            model_name='immobile',
            name='status',
            field=models.CharField(choices=[('Available', 'Disponível'), ('Rented', 'Alugada'), ('Unavailable', 'Indisponível')], default='Available', max_length=15),
        ),
    ]
