# Generated by Django 5.2 on 2025-04-22 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobile', '0005_alter_immobile_property_type_alter_immobile_status'),
        ('owner', '0004_remove_owner_member_since_alter_owner_about_me_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immobile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='owner.owner'),
        ),
    ]
