# Generated by Django 5.2 on 2025-04-22 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immobile', '0005_alter_immobile_property_type_alter_immobile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='immobilephoto',
            name='image',
        ),
        migrations.AddField(
            model_name='immobilephoto',
            name='content_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='immobilephoto',
            name='image_blob',
            field=models.BinaryField(default=bytes),
        ),
        migrations.AlterField(
            model_name='immobilephoto',
            name='immobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos_blob', to='immobile.immobile'),
        ),
    ]
